default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bot_reminder_development

test:
  <<: *default
  database: bot_reminder_test

production:
  <<: *default
  database: bot_reminder_production
  # username: bot_reminder
  # password: <%= ENV['BOT_REMINDER_DATABASE_PASSWORD'] %>
